[gdrive1]
type = drive
scope = drive
token = {"access_token":"ya29.a0AQvPyIOFPX35SbSKa6ee4jWICJorfRIaZ12RJOPEUo49Cn7otiX7HPl18cDSdBFAMmmBesghkpXyZiey9y7YgHIQ2d2rG8RdRfgO0X4q1LxQrbukBjAc2oIk0QfbnfNcTJrovcugCAVIlS7ie9W8xpAEbMlGh3N1EUnYr7z5ZPBfNB00kGzUEl4v7RfFoGgQy10070rQaCgYKAYMSARYSFQHGX2MiZPslCOKPohQgPcQaiuVUuA0207","token_type":"Bearer","refresh_token":"1//0eR5bZHgNlkf_CgYIARAAGA4SNwF-L9IrkgdSuqPHLZLV5Z9fJSFtpKpFqNd3IKWfFJtwGipAjAtR_V8V1C5tm-g0AHsgceSI7n0","expiry":"2026-05-18T03:57:26.567194976+07:00","expires_in":3599}

[gdrive2]
type = drive
scope = drive
token = {"access_token":"ya29.a0AQvPyIN6_tMFTs2n-iurvNLRpfqg8-qQ-i4XuwByGZPHQaPXFG4C-ynICB356Rsxb6qZDL-9LqX1EyjBbUPxKPxIQtKA2ibvLNDqTCu-SLFGPj51c5Dpy8vtZcHkkJpZs4_9vN7dnevPf45uJ0ve7vnVspuHFZLzM2IrEe6FriCRxbp37Fa6pov2c7ffjHmav-TGdgcaCgYKAXwSARUSFQHGX2MigN-iF9vqcsj7nXzUDcwPWg0206","token_type":"Bearer","refresh_token":"1//0eA5AIqsXzp4zCgYIARAAGA4SNwF-L9Ir2xKrHg-Y2HdqlWM5ghlYVj1OlPcSS3FOrr2l8rdY2-Ahbb42viJeVsEm9GFQfMJrfE0","expiry":"2026-05-18T03:51:29.7642329+07:00","expires_in":3599}
team_drive = 

[union_library]
type = union
upstreams = gdrive1: gdrive2:

