cursor #181c20
cursor_text_color #41474d

foreground            #181c20
background            #f7f9ff
selection_foreground  #ffffff
selection_background  #b8c8d9
url_color             #28638a

color0   #101417
color1   #831336
color2   #076713
color3   #a59c00
color4   #246590
color5   #bcdef4
color6   #28638a
color7   #242526
color8   #717375
color9   #bc4667
color10  #21972f
color11  #b3a901
color12  #2e75a6
color13  #bcdef4
color14  #739ab3
color15  #c9cccf
