cursor #f0dedd
cursor_text_color #d7c1c0

foreground            #f0dedd
background            #1a1111
selection_foreground  #442928
selection_background  #e7bdba
url_color             #ffb3b0

color0   #1a1111
color1   #ff7372
color2   #9aff7f
color3   #ffe472
color4   #f29b98
color5   #763532
color6   #ffb3b0
color7   #fff0ef
color8   #a59999
color9   #ff9f9f
color10  #b8ffa5
color11  #ffeda5
color12  #ffbebb
color13  #ffc9c7
color14  #ffdcdb
color15  #fff8f8
