cursor #e2e2e9
cursor_text_color #c4c6d0

foreground            #e2e2e9
background            #111318
selection_foreground  #293041
selection_background  #bfc6dc
url_color             #adc6ff

color0   #111318
color1   #ff7299
color2   #7fff92
color3   #fff872
color4   #94b1f2
color5   #304576
color6   #adc6ff
color7   #eff4ff
color8   #999da5
color9   #ff9fb9
color10  #a5ffb3
color11  #fffaa5
color12  #b9ceff
color13  #c5d7ff
color14  #dae5ff
color15  #f8faff
