# Import config files
source=execs.conf
source=general.conf
source=rules.conf
source=keybinds.conf
source=touchpad.conf
source=hyprcursor.conf

# HyprEmoji config
env = PATH,/home/phong/.local/bin:/usr/local/bin:/usr/bin
source = ~/.config/hypremoji/hypremoji.conf
