# wallpaper

$wall = ~/Pictures/screenshot.png

# background

background {
monitor =
path = $wall
blur_size = 5
blur_passes = 2
noise = 0.0117
contrast = 1.6000
brightness = 0.5000
vibrancy = 0.2500
vibrancy_darkness = 0.1000
}

# profile

image {
monitor =
path = ~/Pictures/art_download.png
size = 260
border_size = 0
rounding = 0
rotate = 0
reload_time = 0
position = 0, -130
halign = center
valign = center
}
# password-box

input-field {
monitor =
size = 250, 50
outline_thickness = 3
dots_size = 0.26
dots_spacing = 0.15
dots_center = true
dots_rounding = -1
outer_color = rgba(00aaee44)
inner_color = rgba(11111b29)
font_color = rgb(00bbff)
fade_on_empty = true
hide_input = false
rounding = -1
check_color = rgb(da9367)
fail_color = rgb(e36b88)
position = 0, 125
halign = center
valign = bottom
}

# time

label {
monitor =
text = cmd[update:2000] echo $(date +"%H:%M:%S")
color = rgb(00bbff)
font_size = 140
font_family = PowerofDragon-Regular.ttf
position = 0, 300
halign = center
valign = center
}

# date

label {
monitor =
text = cmd[update:1000] echo $(date +"%a, %d %b %y")
color = rgb(eeddff)
font_size = 48
font_family = power of dragon regular
position = 0, 160
halign = center
valign = center
}

# name

label {
monitor =
text = hon¤©
color = rgb(00bbff)
font_size = 70
font_family = power of dragon regular
position = 0, -300
halign = center
valign = center
}

# border

label {
monitor =
text = attack on titan
color = rgb(ffffff)
font_size = 80
font_family = goth titan
position = 0, 80
halign = center
valign = center
}

# lock logo

label {
monitor =
text = 
color = rgb(cfcfcf)
font_size = 30
font_family = power of dragon regular
position = 0, 50
halign = center
valign = bottom
}

# current song

label {
monitor =
text = cmd[update:1000] echo "$(~/.local/bin/now-playing max_length=50)"
color = rgb(22, 200, 255)
font_size = 50
font_family = power of dragon regular
position = 0, -20
halign = center
valign = top
}

