#################
### Workspace ###
#################
windowrule {
  name = TradingView
  match:class = ^TradingView$
  float = true
}
windowrule {
  name = zathura
  match:class = ^org\.pwmt\.zathura$
  workspace = 4
}

windowrule {
  name = libreoffice
  match:class = ^libreoffice.*
  workspace = 4
}

windowrule {
  name = mpv
  match:class = ^mpv$
  workspace = 1
  float = true
}

windowrule {
  name = qbittorrent
  match:class = ^org\.qbittorrent\.qBittorrent$
  match:title = ^qBittorrent.*
  workspace = 5
  tile = true
}

windowrule {
  name = vesktop
  match:class = ^vesktop$
  workspace = 4
}

windowrule {
  name = steam-games
  match:class = ^steam_app_\d+$
  workspace = 10
  monitor = 1
  fullscreen = true
}

workspace = 10, border:false, rounding:false

###############
### Windows ###
###############

windowrule {
  name = imv
  match:class = ^imv$
  float = true
  center = true
  size = 75% 75%
}

windowrule {
  name = kitty
  match:class = ^kitty$
  float = false
  size = 64% 70%
}

windowrule {
  name = nemo
  match:class = ^nemo$
  float = true
}

windowrule {
  name = vscode
  match:class = ^code$
  float = true
}

windowrule {
  name = timecanvas
  match:class = ^TimeCanvas$
  float = true
  center = true
}

windowrule {
  name = picture-in-picture
  match:title = ^Picture-in-Picture$
  float = true
}

windowrule {
  name = zen-save
  match:class = ^zen-alpha$
  match:title = ^Save Image$
  size = 800 600
}

windowrule {
  name = openutau-dialogs
  match:class = ^OpenUtau$
  match:title = ^(Open\.\.\.|Save As\.\.\.)$
  float = true
  center = true
  size = 60% 60%
}

windowrule {
  name = file-dialogs
  match:title = ^Open File.*
  float = true
}

windowrule {
  name = no-maximize
  match:class = .*
  maximize = Off
}

windowrule {
  name = desktop-gremlins
  match:title = ilgwg_desktop_gremlins.py
  no_blur = true
  no_shadow = true
}

##################
### LayerRules ###
##################

layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace rofi
layerrule = blur on, match:namespace notifications

layerrule = ignore_alpha on, match:namespace waybar
layerrule = ignore_alpha on, match:namespace rofi
layerrule = ignore_alpha on, match:namespace notifications

layerrule = dim_around on, match:namespace rofi

# vim: set ft=hyprlang :

